# Generated by Django 4.1.7 on 2023-03-28 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 28, 14, 59, 46, 104985)),
        ),
    ]
